const WORDS = [
  "anchor",
  "ant",
  "apple",
  "avocado",
  "backpack",
  "bacon",
  "badger",
  "baguette",
  "banana",
  "basket",
  "bed",
  "bird",
  "blanket",
  "book",
  "bottle",
  "bowl",
  "box",
  "broccoli",
  "brush",
  "bucket",
  "butter",
  "cake",
  "camel",
  "camera",
  "candle",
  "carrot",
  "cat",
  "chair",
  "cheese",
  "cherry",
  "chicken",
  "chocolate",
  "clock",
  "cloud",
  "coconut",
  "coffee",
  "comb",
  "cookie",
  "cow",
  "croissant",
  "cucumber",
  "cup",
  "cushion",
  "deer",
  "desk",
  "diamond",
  "dog",
  "donut",
  "door",
  "duck",
  "eagle",
  "egg",
  "elephant",
  "feather",
  "fish",
  "flower",
  "fork",
  "fox",
  "frog",
  "garlic",
  "giraffe",
  "glass",
  "goat",
  "grape",
  "hamburger",
  "hammer",
  "hedgehog",
  "honey",
  "horse",
  "hot-dog",
  "jacket",
  "juice",
  "kangaroo",
  "key",
  "koala",
  "ladder",
  "lamp",
  "leaf",
  "lemon",
  "lime",
  "lion",
  "lizard",
  "llama",
  "mango",
  "milk",
  "mirror",
  "monkey",
  "mouse",
  "muffin",
  "mug",
  "mushroom",
  "needle",
  "noodle",
  "onion",
  "owl",
  "oyster",
  "pancake",
  "panda",
  "paper",
  "pea",
  "peach",
  "pear",
  "pen",
  "pencil",
  "penguin",
  "pepper",
  "piano",
  "pig",
  "pigeon",
  "pillow",
  "pineapple",
  "pizza",
  "plate",
  "popcorn",
  "potato",
  "pumpkin",
  "rabbit",
  "ring",
  "rope",
  "seal",
  "shark",
  "sheep",
  "shoe",
  "sloth",
  "snail",
  "snake",
  "soap",
  "sock",
  "soup",
  "spaghetti",
  "spider",
  "spoon",
  "stone",
  "strawberry",
  "sushi",
  "table",
  "tea",
  "tomato",
  "tree",
  "turtle",
  "umbrella",
  "waffle",
  "wallet",
  "watch",
  "watermelon",
  "whale",
  "wheel",
  "window",
  "wolf",
  "yogurt",
] as const;

type ExtraWord = "rock";

type Word = (typeof WORDS)[number] | ExtraWord;

const LOSING_COMBINATIONS: [Word, Word, Word?][] = [
  ["chair", "rock"],
  ["cup", "rock"],
  ["hamburger", "rock"],
  ["jacket", "rock"],
  // ["juice", "backpack"],
  ["hedgehog", "rock"],
  ["lion", "rock"],
  ["pancake", "rock"],
  ["rope", "rock"],
  ["shark", "rock"],
  ["umbrella", "rock"],
  ["anchor", "butter", "rock"],
  ["anchor", "cookie", "window"],
  ["anchor", "cucumber", "cloud"],
  ["anchor", "hammer", "potato"],
  ["anchor", "key", "book"],
  ["anchor", "oyster", "rock"],
  ["anchor", "seal", "eagle"],
  ["anchor", "soup", "piano"],
  ["apple", "anchor", "ant"],
  ["apple", "clock", "ant"],
  ["apple", "juice", "ant"],
  ["apple", "juice", "backpack"],
  ["apple", "seal", "umbrella"],
  ["avocado", "anchor", "apple"],
  ["avocado", "anchor", "flower"],
  ["avocado", "anchor", "kangaroo"],
  ["avocado", "anchor", "pancake"],
  ["avocado", "bacon", "backpack"],
  ["avocado", "juice", "ant"],
  ["avocado", "juice", "backpack"],
  ["avocado", "milk", "potato"],
  ["avocado", "paper", "deer"],
  ["avocado", "soup", "lemon"],
  ["bacon", "juice", "backpack"],
  ["bacon", "soup", "diamond"],
  ["bacon", "soup", "wheel"],
  ["banana", "box", "lemon"],
  ["banana", "milk", "diamond"],
  ["banana", "needle", "cake"],
  ["banana", "stone", "potato"],
  ["bed", "box", "sheep"],
  ["bird", "box", "camel"],
  ["bird", "wheel", "cow"],
  ["blanket", "stone", "anchor"],
  ["book", "anchor", "penguin"],
  ["bottle", "anchor", "muffin"],
  ["bottle", "anchor", "paper"],
  ["bottle", "anchor", "rock"],
  ["bottle", "wheel", "cat"],
  ["bowl", "anchor", "spider"],
  ["broccoli", "ring", "needle"],
  ["bucket", "hammer", "sushi"],
  ["bucket", "ring", "cow"],
  ["bucket", "seal", "spider"],
  ["butter", "key", "croissant"],
  ["camel", "monkey", "spaghetti"],
  ["camel", "snake", "feather"],
  ["camel", "snake", "sushi"],
  ["candle", "key", "deer"],
  ["carrot", "cookie", "ant"],
  ["carrot", "onion", "broccoli"],
  ["carrot", "popcorn", "cookie"],
  ["carrot", "seal", "rock"],
  ["carrot", "spaghetti", "wheel"],
  ["carrot", "stone", "needle"],
  ["cat", "key", "book"],
  ["cat", "lion", "cup"],
  ["cat", "paper", "bowl"],
  ["cat", "snake", "ring"],
  ["chair", "anchor", "shoe"],
  ["cherry", "chocolate", "box"],
  ["cherry", "lemon", "window"],
  ["cherry", "pencil", "fox"],
  ["chicken", "bird", "cheese"],
  ["chicken", "bird", "pumpkin"],
  ["chicken", "needle", "bacon"],
  ["chicken", "oyster", "honey"],
  ["chocolate", "wheel", "cat"],
  ["coffee", "tea", "duck"],
  ["cow", "popcorn", "piano"],
  ["cow", "ring", "eagle"],
  ["cow", "snake", "lion"],
  ["cow", "soup", "dog"],
  ["cup", "anchor", "hedgehog"],
  ["cup", "needle", "spaghetti"],
  ["cup", "paper", "penguin"],
  ["cup", "soup", "piano"],
  ["deer", "anchor", "cow"],
  ["diamond", "anchor", "pen"],
  ["diamond", "wheel", "book"],
  ["dog", "paper", "pigeon"],
  ["eagle", "anchor", "cow"],
  ["eagle", "clock", "elephant"],
  ["egg", "anchor", "dog"],
  ["egg", "soup", "coconut"],
  ["elephant", "anchor", "milk"],
  ["elephant", "feather", "horse"],
  ["feather", "anchor", "candle"],
  ["feather", "seal", "honey"],
  ["flower", "seal", "rock"],
  ["fork", "key", "rock"],
  ["fork", "paper", "rock"],
  ["fox", "clock", "tomato"],
  ["fox", "soup", "elephant"],
  ["frog", "basket", "pumpkin"],
  ["frog", "clock", "avocado"],
  ["frog", "clock", "cake"],
  ["garlic", "milk", "sushi"],
  ["garlic", "stone", "book"],
  ["glass", "anchor", "flower"],
  ["goat", "paper", "comb"],
  ["grape", "needle", "key"],
  ["hamburger", "key", "chocolate"],
  ["hamburger", "soup", "garlic"],
  ["hammer", "ring", "soap"],
  ["hedgehog", "brush", "table"],
  ["hedgehog", "ring", "camel"],
  ["horse", "anchor", "rock"],
  ["horse", "rope", "elephant"],
  ["horse", "wallet", "shark"],
  ["hot-dog", "anchor", "lamp"],
  ["juice", "tea", "mushroom"],
  ["kangaroo", "horse", "honey"],
  ["kangaroo", "snake", "rock"],
  ["koala", "key", "dog"],
  ["ladder", "clock", "apple"],
  ["ladder", "stone", "fox"],
  ["lemon", "box", "egg"],
  ["lemon", "clock", "window"],
  ["lemon", "cookie", "basket"],
  ["lemon", "onion", "tree"],
  ["lemon", "seal", "snake"],
  ["lemon", "snake", "diamond"],
  ["lemon", "soup", "cherry"],
  ["lemon", "soup", "strawberry"],
  ["lemon", "watermelon", "hamburger"],
  ["lemon", "wheel", "soup"],
  ["lime", "seal", "spider"],
  ["lion", "box", "whale"],
  ["lion", "hedgehog", "ant"],
  ["lion", "mirror", "giraffe"],
  ["lion", "rope", "camel"],
  ["lion", "stone", "cup"],
  ["llama", "anchor", "coconut"],
  ["mango", "apple", "pencil"],
  ["mango", "butter", "rock"],
  ["mango", "fork", "whale"],
  ["mango", "key", "sloth"],
  ["mango", "lemon", "baguette"],
  ["mango", "seal", "yogurt"],
  ["milk", "bacon", "diamond"],
  ["milk", "cake", "chocolate"],
  ["milk", "monkey", "lion"],
  ["milk", "tea", "diamond"],
  ["monkey", "wheel", "egg"],
  ["monkey", "wheel", "hot-dog"],
  ["muffin", "anchor", "cherry"],
  ["mug", "anchor", "grape"],
  ["noodle", "hammer", "grape"],
  ["owl", "bird", "baguette"],
  ["oyster", "brush", "blanket"],
  ["pancake", "clock", "ant"],
  ["pancake", "pizza", "carrot"],
  ["panda", "monkey", "bottle"],
  ["panda", "snake", "yogurt"],
  ["paper", "anchor", "pumpkin"],
  ["paper", "seal", "soup"],
  ["pea", "comb", "pineapple"],
  ["pea", "tea", "panda"],
  ["peach", "anchor", "feather"],
  ["peach", "book", "spaghetti"],
  ["peach", "lime", "llama"],
  ["peach", "milk", "rock"],
  ["peach", "pencil", "basket"],
  ["peach", "pepper", "llama"],
  ["pear", "anchor", "cow"],
  ["pear", "butter", "soap"],
  ["pencil", "key", "cushion"],
  ["penguin", "anchor", "pea"],
  ["penguin", "bird", "watch"],
  ["piano", "anchor", "sock"],
  ["piano", "anchor", "spoon"],
  ["pig", "box", "anchor"],
  ["pig", "brush", "carrot"],
  ["pig", "milk", "giraffe"],
  ["pigeon", "anchor", "rock"],
  ["pigeon", "key", "rock"],
  ["pizza", "anchor", "pencil"],
  ["popcorn", "key", "rock"],
  ["popcorn", "wheel", "book"],
  ["potato", "brush", "ant"],
  ["potato", "comb", "pumpkin"],
  ["potato", "cucumber", "chocolate"],
  ["potato", "ring", "llama"],
  ["rope", "key", "tea"],
  ["seal", "watch", "llama"],
  ["shark", "egg", "monkey"],
  ["shark", "glass", "rock"],
  ["shark", "mirror", "umbrella"],
  ["shark", "ring", "chicken"],
  ["shark", "ring", "lime"],
  ["shark", "rope", "comb"],
  ["shark", "snake", "hamburger"],
  ["shark", "sock", "cloud"],
  ["shark", "wheel", "grape"],
  ["shark", "wolf", "cushion"],
  ["sheep", "anchor", "cushion"],
  ["sheep", "brush", "cheese"],
  ["sheep", "seal", "pear"],
  ["snail", "anchor", "chocolate"],
  ["snake", "anchor", "fox"],
  ["soap", "anchor", "onion"],
  ["sock", "key", "hamburger"],
  ["soup", "anchor", "chicken"],
  ["soup", "anchor", "sheep"],
  ["soup", "butter", "lamp"],
  ["strawberry", "wheel", "owl"],
  ["strawberry", "wheel", "tree"],
  ["sushi", "cucumber", "strawberry"],
  ["sushi", "soup", "rock"],
  ["table", "seal", "sheep"],
  ["table", "soap", "horse"],
  ["tomato", "cookie", "pencil"],
  ["tomato", "lemon", "spaghetti"],
  ["tomato", "snake", "candle"],
  ["tree", "needle", "watch"],
  ["umbrella", "box", "spider"],
  ["umbrella", "seal", "duck"],
  ["watermelon", "grape", "bowl"],
  ["watermelon", "hammer", "rock"],
  ["watermelon", "paper", "desk"],
  ["watermelon", "pear", "giraffe"],
  ["whale", "needle", "wolf"],
  ["window", "anchor", "fox"],
  ["wolf", "snake", "cushion"],
];

const OFFSET = 0;

const LIMIT = 250;

const TOTAL_RUNS = 250;

const USE_RANDOM_ORDER = true;

export { WORDS, LIMIT, OFFSET, TOTAL_RUNS, USE_RANDOM_ORDER, LOSING_COMBINATIONS };
