const WORDS = [
  // "anchor",
  "ant",
  "apple",
  "avocado",
  "backpack",
  "bacon",
  "badger",
  "baguette",
  "banana",
  "basket",
  "bed",
  "bird",
  "blanket",
  "book",
  "bottle",
  "bowl",
  "box",
  "broccoli",
  "brush",
  "bucket",
  "butter",
  "cake",
  "camel",
  "camera",
  "candle",
  "carrot",
  "cat",
  "chair",
  "cheese",
  "cherry",
  "chicken",
  "chocolate",
  "clock",
  "cloud",
  "coconut",
  "coffee",
  "comb",
  "cookie",
  "cow",
  "croissant",
  "cucumber",
  "cup",
  "cushion",
  "deer",
  "desk",
  "diamond",
  "dog",
  "donut",
  "door",
  "duck",
  "eagle",
  "egg",
  "elephant",
  "feather",
  "fish",
  "flower",
  "fork",
  "fox",
  "frog",
  "garlic",
  "giraffe",
  "glass",
  "goat",
  "grape",
  "hamburger",
  "hammer",
  "hedgehog",
  "honey",
  "horse",
  "hot-dog",
  "jacket",
  "juice",
  "kangaroo",
  "key",
  "koala",
  "ladder",
  "lamp",
  "leaf",
  "lemon",
  "lime",
  "lion",
  "lizard",
  "llama",
  "mango",
  "milk",
  "mirror",
  "monkey",
  "mouse",
  "muffin",
  "mug",
  "mushroom",
  "needle",
  "noodle",
  "onion",
  "owl",
  "oyster",
  "pancake",
  "panda",
  "paper",
  "peach",
  "pear",
  "pen",
  "pencil",
  "penguin",
  "pepper",
  "piano",
  "pig",
  "pigeon",
  "pillow",
  "pineapple",
  "pizza",
  "plate",
  "popcorn",
  "potato",
  "pumpkin",
  "rabbit",
  "ring",
  "rope",
  "seal",
  "shark",
  "sheep",
  "shoe",
  "sloth",
  "snail",
  "snake",
  "soap",
  "sock",
  "soup",
  "spaghetti",
  "spider",
  "spoon",
  "stone",
  "strawberry",
  "sushi",
  "table",
  "tea",
  "tomato",
  "tree",
  "turtle",
  "umbrella",
  "waffle",
  "wallet",
  "watch",
  "watermelon",
  "whale",
  "wheel",
  "window",
  "wolf",
  "yogurt",
] as const;

type ExtraWord = "rock" | "anchor";

type Word = (typeof WORDS)[number] | ExtraWord;

const LOSING_COMBINATIONS: [Word, Word, Word?][] = [
  ["umbrella", "rock"],
  ["apple", "anchor", "ant"],
  ["apple", "clock", "ant"],
  ["avocado", "anchor", "apple"],
  ["avocado", "bacon", "backpack"],
  ["avocado", "soup", "lemon"],
  ["bacon", "soup", "diamond"],
  ["bed", "box", "sheep"],
  ["bird", "box", "camel"],
  ["bird", "wheel", "cow"],
  ["camel", "monkey", "spaghetti"],
  ["camel", "snake", "sushi"],
  ["carrot", "onion", "broccoli"],
  ["carrot", "popcorn", "cookie"],
  ["carrot", "spaghetti", "wheel"],
  ["cherry", "chocolate", "box"],
  ["cherry", "lemon", "window"],
  ["chicken", "bird", "cheese"],
  ["chicken", "bird", "pumpkin"],
  ["chicken", "oyster", "honey"],
  ["chocolate", "wheel", "cat"],
  ["coffee", "tea", "duck"],
  ["cow", "popcorn", "piano"],
  ["diamond", "wheel", "book"],
  ["egg", "soup", "coconut"],
  ["hamburger", "soup", "garlic"],
  ["kangaroo", "snake", "rock"],
  ["lemon", "box", "egg"],
  ["lemon", "onion", "tree"],
  ["lemon", "snake", "diamond"],
  ["lemon", "soup", "cherry"],
  ["lemon", "soup", "strawberry"],
  ["lemon", "watermelon", "hamburger"],
  ["lemon", "wheel", "soup"],
  ["mango", "apple", "pencil"],
  ["mango", "lemon", "baguette"],
  ["milk", "cake", "chocolate"],
  ["milk", "tea", "diamond"],
  ["monkey", "wheel", "egg"],
  ["monkey", "wheel", "hot-dog"],
  ["owl", "bird", "baguette"],
  ["pancake", "pizza", "carrot"],
  ["panda", "monkey", "bottle"],
  ["peach", "book", "spaghetti"],
  ["peach", "milk", "rock"],
  ["peach", "pepper", "llama"],
  ["pig", "milk", "giraffe"],
  ["popcorn", "wheel", "book"],
  ["strawberry", "wheel", "owl"],
  ["tomato", "cookie", "pencil"],
  ["tomato", "lemon", "spaghetti"],
  ["umbrella", "box", "spider"],
  ["watermelon", "pear", "giraffe"],
];

const LIMIT = 250;

const TOTAL_RUNS = 1;

const USE_RANDOM_ORDER = false;

export { WORDS, LIMIT, TOTAL_RUNS, USE_RANDOM_ORDER, LOSING_COMBINATIONS };
